Repository zero-to-mastery/webblocks-2022, pull requests merged in 2022-10, with the labels that each got.

#36 Added wink animation
  src/blocks/Sunainacode/face.css
  src/blocks/Sunainacode/index.html
  src/blocks/Sunainacode/meta.json
Labels: Change Requested

#50 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, question

#59 Kwiczling
  src/blocks/kwiczling/icon.png
  src/blocks/kwiczling/index.html
  src/blocks/kwiczling/meta.json
  src/blocks/kwiczling/script.js
  src/blocks/kwiczling/style.css
Labels: Change Requested

#52 conor-v switch box
  src/blocks/conor-v/icon.png
  src/blocks/conor-v/img/fire.jpg
  src/blocks/conor-v/img/water.jpg
  src/blocks/conor-v/index.html
  src/blocks/conor-v/meta.json
  src/blocks/conor-v/script.js
  src/blocks/conor-v/style.css
Labels: Change Requested

#81 Nuha directory in root moved to blocks/src to resolve directory issues
  src/blocks/nuha/app.css
  src/blocks/nuha/app.js
  src/blocks/nuha/icon.png
  src/blocks/nuha/icons/connect.png
  src/blocks/nuha/icons/inspired.png
  src/blocks/nuha/icons/job.png
  src/blocks/nuha/icons/portfolio.png
  src/blocks/nuha/icons/resources.png
  src/blocks/nuha/icons/study.png
  src/blocks/nuha/icons/typing.png
  src/blocks/nuha/index.html
  src/blocks/nuha/meta.json
Labels: invalid

#84 add settings button to my block
  src/blocks/kwiczling/gear.png
  src/blocks/kwiczling/index.html
  src/blocks/kwiczling/script.js
  src/blocks/kwiczling/style.css
Labels: invalid

#85 hacktoberfest second webcomp
  src/blocks/conor-v2/icon.png
  src/blocks/conor-v2/img/codepen.svg
  src/blocks/conor-v2/img/dribbble.svg
  src/blocks/conor-v2/img/facebook.svg
  src/blocks/conor-v2/img/instagram.svg
  src/blocks/conor-v2/img/twitter.svg
  src/blocks/conor-v2/index.html
  src/blocks/conor-v2/meta.json
  src/blocks/conor-v2/style.css
Labels: Change Requested

#78 Typewriter component bby Luis Pellizzon
  src/blocks/LuisPellizzon/icon.png
  src/blocks/LuisPellizzon/index.html
  src/blocks/LuisPellizzon/main.css
  src/blocks/LuisPellizzon/meta.json
  src/blocks/LuisPellizzon/writer.js
Labels: question

#96 Added web block for countdown timer.
  src/blocks/leocsdev4/icon.png
  src/blocks/leocsdev4/index.html
  src/blocks/leocsdev4/index.js
  src/blocks/leocsdev4/meta.json
  src/blocks/leocsdev4/style.css
Labels: Change Requested

#98 Added Calculator webpage
  src/blocks/AnubhavChakraborty/script.js
Labels: invalid

#89 Add timeline block element
  src/blocks/danicc/icon.png
  src/blocks/danicc/index.html
  src/blocks/danicc/meta.json
  src/blocks/danicc/script.js
  src/blocks/danicc/styles.css
Labels: Change Requested

#93 henrykhosasih VirtuCard
  src/blocks/henrykhosasih/icon.png
  src/blocks/henrykhosasih/images/mastercard-logo.png
  src/blocks/henrykhosasih/index.html
  src/blocks/henrykhosasih/meta.json
  src/blocks/henrykhosasih/scripts.js
  src/blocks/henrykhosasih/styles.css
Labels: question

#100 new commit
  src/blocks/RajMishra2/app.js
  src/blocks/RajMishra2/icon.gif
  src/blocks/RajMishra2/icon.png
  src/blocks/RajMishra2/index.html
  src/blocks/RajMishra2/meta.json
  src/blocks/RajMishra2/style.css
Labels: Change Requested

#116 Simple To Do List !
  src/blocks/yashraj2003e/app.js
  src/blocks/yashraj2003e/bg3.jpg
  src/blocks/yashraj2003e/css/font-awesome.css
  src/blocks/yashraj2003e/css/style.css
  src/blocks/yashraj2003e/fonts/FontAwesome.otf
  src/blocks/yashraj2003e/fonts/fontawesome-webfont.eot
  src/blocks/yashraj2003e/fonts/fontawesome-webfont.svg
  src/blocks/yashraj2003e/fonts/fontawesome-webfont.ttf
  src/blocks/yashraj2003e/fonts/fontawesome-webfont.woff
  src/blocks/yashraj2003e/fonts/fontawesome-webfont.woff2
  src/blocks/yashraj2003e/index.html
  src/blocks/yashraj2003e/meta.json
  src/blocks/yashraj2003e/screen.png
Labels: Change Requested

#124 Employee database
  src/blocks/MarkL50/employeeDatabase.css
  src/blocks/MarkL50/employeeDatabase.html
  src/blocks/MarkL50/employeeDatabase.js
  src/blocks/MarkL50/icon.png
  src/blocks/MarkL50/meta.json
Labels: Change Requested

#103 'first-pull'
  src/blocks/Md-Aquib/icon.PNG
  src/blocks/Md-Aquib/index.html
  src/blocks/Md-Aquib/meta.json
  src/blocks/Md-Aquib/style.css
Labels: bug

#105 Background Based On Time
  src/blocks/siddharthsinghvats4/icon.png
  src/blocks/siddharthsinghvats4/index.html
  src/blocks/siddharthsinghvats4/index.js
  src/blocks/siddharthsinghvats4/meta.json
  src/blocks/siddharthsinghvats4/style.css
Labels: Change Requested

#111 month-animation
  src/blocks/ab-3/icon.png
  src/blocks/ab-3/index.html
  src/blocks/ab-3/meta.json
  src/blocks/ab-3/style.css
  src/blocks/meetkavathiya/icon.png
  src/blocks/meetkavathiya/index.html
  src/blocks/meetkavathiya/main.js
  src/blocks/meetkavathiya/meta.json
  src/blocks/meetkavathiya/style.css
  src/blocks/mk2/icon.png
  src/blocks/mk2/index.html
  src/blocks/mk2/main.js
  src/blocks/mk2/meta.json
  src/blocks/mk2/style.css
Labels: Change Requested

#107 commit-1
  src/blocks/meetkavathiya/icon.png
  src/blocks/meetkavathiya/index.html
  src/blocks/meetkavathiya/main.js
  src/blocks/meetkavathiya/style.css
Labels: Change Requested

#141 created amazon app sign-up page
  src/blocks/mariko971/App-fonts/amazonember_bd-webfont.woff
  src/blocks/mariko971/App-fonts/amazonember_bd-webfont.woff2
  src/blocks/mariko971/App-fonts/amazonember_rg-webfont.woff
  src/blocks/mariko971/App-fonts/amazonember_rg-webfont.woff2
  src/blocks/mariko971/icon.png
  src/blocks/mariko971/index.css
  src/blocks/mariko971/index.html
  src/blocks/mariko971/index.js
  src/blocks/mariko971/marikodev.png
  src/blocks/mariko971/meta.json
Labels: question

#143 Adding Object detection through webcamp by ml5.js library
  src/blocks/SudiptoMlJS/icon.png
  src/blocks/SudiptoMlJS/index.html
  src/blocks/SudiptoMlJS/meta.json
  src/blocks/SudiptoMlJS/script.js
  src/blocks/SudiptoMlJS/style.css
Labels: Change Requested

#126 Added Black jack
  src/blocks/shemils/icon.png
  src/blocks/shemils/images/1.png
  src/blocks/shemils/images/10.png
  src/blocks/shemils/images/11.png
  src/blocks/shemils/images/12.png
  src/blocks/shemils/images/13.png
  src/blocks/shemils/images/2.png
  src/blocks/shemils/images/3.png
  src/blocks/shemils/images/4.png
  src/blocks/shemils/images/5.png
  src/blocks/shemils/images/6.png
  src/blocks/shemils/images/7.png
  src/blocks/shemils/images/8.png
  src/blocks/shemils/images/9.png
  src/blocks/shemils/images/back.jpg
  src/blocks/shemils/images/background.png
  src/blocks/shemils/index.html
  src/blocks/shemils/meta.json
  src/blocks/shemils/script.js
  src/blocks/shemils/style.css
Labels: Change Requested

#125 Digital Clock
  src/blocks/SahilRawat/icon.png
  src/blocks/SahilRawat/index.html
  src/blocks/SahilRawat/meta.json
  src/blocks/SahilRawat/script.js
  src/blocks/SahilRawat/style.css
Labels: Change Requested

#157 New Commit
  src/blocks/RajMishra3/app.js
  src/blocks/RajMishra3/icon.gif
  src/blocks/RajMishra3/icon.png
  src/blocks/RajMishra3/index.html
  src/blocks/RajMishra3/meta.json
  src/blocks/RajMishra3/style.css
Labels: question

#163 Notes app
  src/blocks/Ayush-Dahala/icon.png
  src/blocks/Ayush-Dahala/index.html
  src/blocks/Ayush-Dahala/index.js
  src/blocks/Ayush-Dahala/meta.json
Labels: Change Requested

#192 add my block to the project - responsive header
  src/blocks/kwiczling2/index.html
  src/blocks/kwiczling2/logo.png
  src/blocks/kwiczling2/script.js
  src/blocks/kwiczling2/style.css
Labels: Change Requested

#228 Stats
  src/blocks/cherbear263-2/icon.png
  src/blocks/cherbear263-2/index.html
  src/blocks/cherbear263-2/meta.json
  src/blocks/cherbear263-2/scripts.js
  src/blocks/cherbear263-2/style.css
  src/blocks/cherbear263/index.html
Labels: Change Requested

#252 9112 michael
  src/blocks/9112Michael/icon.png
  src/blocks/9112Michael/index.html
  src/blocks/9112Michael/meta.json
  src/blocks/9112Michael/style.css
Labels: question

#231 feat: halloween navbar 🚀
  src/blocks/phyllis-wb-1/index.html
  src/blocks/phyllis-wb-1/meta.json
  src/blocks/phyllis-wb-1/scripts.js
  src/blocks/phyllis-wb-1/styles.css
Labels: Change Requested

#255 Uploading flexible HactoberNavBar files
  src/blocks/betiniakarandut02/background.png
  src/blocks/betiniakarandut02/icon.png
  src/blocks/betiniakarandut02/index.html
  src/blocks/betiniakarandut02/meta.json
  src/blocks/betiniakarandut02/style.css
Labels: question

#266 Test
  src/blocks/conda121/icon.PNG
  src/blocks/conda121/index.html
  src/blocks/conda121/meta.json
  src/blocks/conda121/styles.css
Labels: question

#271 feat: dj chai's audio player
  src/blocks/pyllis-wb-2/index.html
  src/blocks/pyllis-wb-2/meta.json
  src/blocks/pyllis-wb-2/scripts.js
  src/blocks/pyllis-wb-2/styles.css
Labels: question

#251 Responsive-Card
  src/blocks/geet/icon.png
  src/blocks/geet/index.html
  src/blocks/geet/meta.json
  src/blocks/geet/style.css
Labels: question, Change Requested

#221 Added progress bar with an animated background of gradients
  src/blocks/IshanGupta/icon.png
  src/blocks/IshanGupta/index.html
  src/blocks/IshanGupta/meta.json
  src/blocks/IshanGupta/script.js
  src/blocks/IshanGupta/style.css
Labels: Change Requested

#243 Gym Landing Page
  src/blocks/Keegan/css/style.css
  src/blocks/Keegan/icon.png
  src/blocks/Keegan/img/img1.avif
  src/blocks/Keegan/img/logo.png
  src/blocks/Keegan/index.html
  src/blocks/Keegan/meta.json
Labels: Change Requested

#278 Added footer
  src/blocks/ankitbajpai65/icon.png
  src/blocks/ankitbajpai65/icons/fb.png
  src/blocks/ankitbajpai65/icons/instagram.png
  src/blocks/ankitbajpai65/icons/youtube.png
  src/blocks/ankitbajpai65/index.html
  src/blocks/ankitbajpai65/meta.json
  src/blocks/ankitbajpai65/style.css
Labels: Change Requested

#301 Create a qoute generator that also change color when clicked.
  src/blocks/EmanuelGustafzon/app.js
  src/blocks/EmanuelGustafzon/icon.png
  src/blocks/EmanuelGustafzon/index.html
  src/blocks/EmanuelGustafzon/meta.json
  src/blocks/EmanuelGustafzon/styles.css
  src/blocks/Geetika/style.css
Labels: Change Requested

#291 feat: responsive card with images that change on click
  src/blocks/phyllis-wb-3/assets/david-billings-85rGc_g6b4E-unsplash.jpg
  src/blocks/phyllis-wb-3/assets/link.svg
  src/blocks/phyllis-wb-3/assets/melanie-dretvic-wblqwJnjepI-unsplash.jpg
  src/blocks/phyllis-wb-3/assets/peter-burdon-jGfZSSnoOHU-unsplash.jpg
  src/blocks/phyllis-wb-3/index.css
  src/blocks/phyllis-wb-3/index.html
  src/blocks/phyllis-wb-3/index.js
  src/blocks/phyllis-wb-3/meta.json
Labels: question

#320 Initial Commit
  src/blocks/avishaan24/avi.js
  src/blocks/avishaan24/icon.png
  src/blocks/avishaan24/index.html
  src/blocks/avishaan24/medium.css
  src/blocks/avishaan24/meta.json
  src/blocks/avishaan24/small.css
  src/blocks/avishaan24/style.css
Labels: Change Requested

#292 updated PR template regarding issue #290
  docs/pull_request_template.md
Labels: Change Requested

#161 Pokemon
  src/blocks/daytonschuh/index.html
  src/blocks/daytonschuh/script.js
  src/blocks/daytonschuh/style.css
Labels: question

#275 Info box w/ Google maps embed
  src/blocks/blitzmartin-3/favicon.ico
  src/blocks/blitzmartin-3/icon.PNG
  src/blocks/blitzmartin-3/index.html
  src/blocks/blitzmartin-3/meta.json
  src/blocks/blitzmartin-3/styles.css
  src/blocks/blitzmartin/data.js
  src/blocks/blitzmartin/index.html
  src/blocks/blitzmartin/styles.css
Labels: Change Requested

#287 Cat adoption page
  src/blocks/TheaAleksovDev4/icon.jpg
  src/blocks/TheaAleksovDev4/images/new1.jpg
  src/blocks/TheaAleksovDev4/images/new2.jpg
  src/blocks/TheaAleksovDev4/images/new3.jpg
  src/blocks/TheaAleksovDev4/index.html
  src/blocks/TheaAleksovDev4/meta.json
  src/blocks/TheaAleksovDev4/script.js
  src/blocks/TheaAleksovDev4/styles.css
Labels: question

#328 Geometric Shapes using CSS
  src/blocks/Ankita Mhatre/icon.png
  src/blocks/Ankita Mhatre/index.html
  src/blocks/Ankita Mhatre/meta.json
  src/blocks/Ankita Mhatre/style.css
Labels: Change Requested

#336 Hacktober
  src/blocks/saga-sanga/index.css
  src/blocks/saga-sanga/index.html
  src/blocks/saga-sanga/script.js
Labels: Change Requested

#318 Carousel component
  src/blocks/Sridarshan/assets/arrow-left.svg
  src/blocks/Sridarshan/assets/arrow-right.svg
  src/blocks/Sridarshan/assets/carousel.png
  src/blocks/Sridarshan/icon.gif
  src/blocks/Sridarshan/index.html
  src/blocks/Sridarshan/meta.json
  src/blocks/Sridarshan/script.js
  src/blocks/Sridarshan/styles.css
Labels: Change Requested

#325 Dice game
  src/blocks/Bhushan(SpiDEr)/game.css
  src/blocks/Bhushan(SpiDEr)/game.html
  src/blocks/Bhushan(SpiDEr)/meta.json
Labels: Change Requested

#345 Birthday-couter
  src/blocks/SuklashanaChetry/icon.png
  src/blocks/SuklashanaChetry/index.html
  src/blocks/SuklashanaChetry/meta.json
  src/blocks/SuklashanaChetry/script.js
  src/blocks/SuklashanaChetry/style.css
Labels: Change Requested

#358 Added an animated carousel webblock
  src/blocks/KshitijSrivastava-2/assets/img/Fifth.jpg
  src/blocks/KshitijSrivastava-2/assets/img/First.jpg
  src/blocks/KshitijSrivastava-2/assets/img/Fourth.jpg
  src/blocks/KshitijSrivastava-2/assets/img/Second.jpg
  src/blocks/KshitijSrivastava-2/assets/img/Third.jpg
  src/blocks/KshitijSrivastava-2/icon.png
  src/blocks/KshitijSrivastava-2/index.html
  src/blocks/KshitijSrivastava-2/meta.json
  src/blocks/KshitijSrivastava-2/script.js
  src/blocks/KshitijSrivastava-2/style.css
Labels: question

#347 Update pull_request_template.md
  docs/pull_request_template.md
Labels: Change Requested

#364 Created Ping Pong Score Keeper Hacktoberfest
  src/blocks/tanishqsindhu/app.js
  src/blocks/tanishqsindhu/icon.png
  src/blocks/tanishqsindhu/index.html
  src/blocks/tanishqsindhu/meta.json
Labels: Change Requested

#341 Added Analog Clock project using HTML, CSS, and JavaScript
  src/blocks/ShubhanshuJha/icon.png
  src/blocks/ShubhanshuJha/index.html
  src/blocks/ShubhanshuJha/meta.json
  src/blocks/ShubhanshuJha/resources/base_file.txt
  src/blocks/ShubhanshuJha/resources/clock.png
  src/blocks/ShubhanshuJha/resources/license.md
  src/blocks/ShubhanshuJha/script.js
  src/blocks/ShubhanshuJha/style.css
Labels: Change Requested

#353 Quote generator
  src/blocks/Slye-Man2/favicon.ico
  src/blocks/Slye-Man2/icon.png
  src/blocks/Slye-Man2/index.html
  src/blocks/Slye-Man2/meta.json
  src/blocks/Slye-Man2/script.js
  src/blocks/Slye-Man2/style.css
Labels: question

#378 new-feature
  maurin7/icon.png
  maurin7/index.html
  maurin7/meta.json
  maurin7/script.js
  maurin7/style.css
Labels: Change Requested, hacktoberfest-accepted

#389 My branch
  src/blocks/nicola/icon.png
  src/blocks/nicola/images/halloween.jpeg
  src/blocks/nicola/index.html
  src/blocks/nicola/meta.json
  src/blocks/nicola/script.js
  src/blocks/nicola/style.css
Labels: Change Requested, hacktoberfest-accepted

#390 Second branch
  src/blocks/nicola2/icon.png
  src/blocks/nicola2/index.html
  src/blocks/nicola2/meta.json
  src/blocks/nicola2/script.js
  src/blocks/nicola2/skeleton.jpeg
  src/blocks/nicola2/style.css
Labels: Change Requested, hacktoberfest-accepted
